variant = "loose"

[[issues]]
file = "src/Provider/ListenerProvider.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Provider/ListenerProvider.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Provider/ListenerProvider.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "no-redundant-method-override"
message = "Redundant method override."
count = 2

[[issues]]
file = "tests/src/Dispatcher/EventDispatcherTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 10

[[issues]]
file = "tests/src/Helper/AnnotatedTestListener.php"
code = "no-redundant-use"
message = "Unused import: `AbstractStoppableEvent`."
count = 1

[[issues]]
file = "tests/src/Provider/ListenerProviderTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 13
